name: stand alone conda test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'branch'
        default: '1.1.x'
        required: true

jobs:
  conda-test:
    name: Conda Test
    # needs: build-sdist
    runs-on: ubuntu-latest
    env:
      PANDAS_VERSION: ${{ github.event.inputs.version }}
    steps:
    - name: Setting conda path
      run: echo ::add-path::$CONDA/bin
    - name: Update conda
      run: |
        conda config --set quiet true --set always_yes true
        conda update -n base -c defaults conda
        conda list
    # - name: Create conda environment
    #   run: |
    #     conda create -n conda-test -y python=3.7 numpy pytz python-dateutil pytest pytest-mock hypothesis nomkl
    #     conda clean --all
    #     conda list
    # - name: get sdist from artifacts
    #   uses: actions/download-artifact@v2
    #   with:
    #     name: pandas-${{ github.event.inputs.version }}.tar.gz
    #     path: pandas/dist/
    - name: Conda Build and Test
      run: |
        # source activate conda-test
        conda build --numpy=1.17.3 --python=3.8 ./recipe --output-folder=/pandas/dist
