# This is a basic workflow that is manually triggered

name: Manual Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        # Friendly description to be shown in the UI instead of 'tag'
        description: 'the pandas tag to release'
        # Default value if no value is explicitly provided
        default: '1.1.x'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  configure:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Set Environment Variables
      run: echo '::set-env name=TAG::${{ github.event.inputs.tag }}'
    - name: Show Environment Variables
      run: echo $TAG
