# This is a basic workflow that is manually triggered

name: Manual Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        # Friendly description to be shown in the UI instead of 'tag'
        description: 'the pandas tag to release'
        # Default value if no value is explicitly provided
        default: '1.1.x'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  configure:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.inputs.tag }}
      GH_USERNAME: ${{ github.actor }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setting git user to Pandas Development Team
      run: |
       git config --global user.email "pandas-dev@python.org"
       git config --global user.name "Pandas Development Team"
    - name: Setting conda path
      run: echo ::add-path::$CONDA/bin
    - name: Update conda
      run: |
        conda config --set quiet true --set always_yes true
        conda update -n base -c defaults conda
        conda list
    - name: Checkout pandas-release
      uses: actions/checkout@v1
    - name: Update conda environment for release process
      run: |
        conda env update -n base --file=environment.yml
        conda list
    - name: Checkout pandas, pandas-wheels and pandas-feedstock
      run: make init-repos
    - name: Tag the release. (This doesn't push the tag)
      run: make tag
    - name: test
      run: git log
    

