# This is a basic workflow that is manually triggered

name: Manual Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        # Friendly description to be shown in the UI instead of 'tag'
        description: 'the pandas tag to release'
        # Default value if no value is explicitly provided
        default: '1.1.x'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  configure:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.inputs.tag }}
      GH_USERNAME: ${{ github.actor }}
      # PATH: ${HOME}/miniconda3/bin:${PATH}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # - name: Setting conda path
    #   run: echo "::set-env name=PATH::${HOME}/miniconda3/bin:${PATH}"
    - name: Update conda path
      run: |
        conda config --set quiet true --set always_yes true
        conda update -n base -c defaults conda
        conda list
    - name: Checkout pandas-release
      uses: actions/checkout@v1
    - name: Set up conda environment for release process
      run: |
        pwd
        ls -la
        cat environment.yml
        conda env create --file=environment.yml
        conda env list
        conda activate pandas-release
        conda list
    - name: Checkout pandas, pandas-wheels and pandas-feedstock
      run: make init-repos
    - name: Tag the release. (This doesn't push the tag)
      run: |
        conda activate pandas-release
        make tag
    - name: test
      run: git log
    

