name: Tag Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '*/15 * * * *'
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'version'
        description: 'the pandas version to release'
        # Default value if no value is explicitly provided
        default: '1.1.3'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tag-release:
    name: Tag the release. (This doesn't push the tag)
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TAG: v${{ github.event.inputs.version }}
      GH_USERNAME: ${{ github.actor }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setting git user to Pandas Development Team
      run: |
       git config --global user.email "pandas-dev@python.org"
       git config --global user.name "Pandas Development Team"
    - name: Checkout pandas-release
      uses: actions/checkout@v2
    - name: Update conda
      uses: ./.github/actions/update-conda
    - name: Update conda environment for release process
      run: |
        conda env update -n base --file=environment.yml
        conda list
    - name: Checkout pandas, pandas-wheels and pandas-feedstock
      run: make init-repos
    - name: Tag the release. (This doesn't push the tag)
      run: make tag
    - name: Show git log
      working-directory: pandas
      run: |
        git log -n 5
    - name: Archive pandas directory to prevent permission loss
      run: tar -czvf tagged_pandas.tar.gz pandas
    - name: Store tagged pandas directory archive as artifact
      uses: actions/upload-artifact@v2
      with:
        name: tagged_pandas
        path: tagged_pandas.tar.gz
        if-no-files-found: error

  check-release-notes:
    name: Check release notes are in sync
    needs: tag-release
    runs-on: ubuntu-latest
    env:
      TAG: v${{ github.event.inputs.version }}
    steps:
    - name: get pandas directory from artifacts
      uses: actions/download-artifact@v2
      with:
        name: tagged_pandas
    - name:  extract achive
      run: tar -xzvf tagged_pandas.tar.gz
    - name: Check release notes are in sync
      working-directory: pandas
      run: git diff --exit-code $TAG master -- doc/source/whatsnew/$TAG.rst

  build-sdist:
    name: Build the sdist
    needs: tag-release
    runs-on: ubuntu-latest
    steps:
    # Remove apt repos that are known to break from time to time 
    # See https://github.com/actions/virtual-environments/issues/323  
    # - name: Remove broken apt repos [Ubuntu]
    #   run: |
    #     for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
    - name: Update for build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get clean
    - name: Checkout pandas-release
      uses: actions/checkout@v2
    - name: Update conda
      uses: ./.github/actions/update-conda
    - name: Update conda environment for build process
      run: |
        conda install -y conda-build conda-verify gcc_linux-64 gxx_linux-64 numpy pytz python-dateutil nomkl Cython
        conda clean --all
        conda list
    - name: get pandas directory from artifacts
      uses: actions/download-artifact@v2
      with:
        name: tagged_pandas
    - name:  extract achive
      run: tar -xzvf tagged_pandas.tar.gz
    - name: build the sdist
      # from ./scripts/build_sdist.sh
      working-directory: pandas
      run: |
        rm -rf dist
        git clean -xfd
        python setup.py clean --quiet
        python setup.py sdist --formats=gztar --quiet
    - name: Store sdist archive as artifact
      uses: actions/upload-artifact@v2
      with:
        name: pandas-${{ github.event.inputs.version }}.tar.gz
        path: pandas/dist/pandas-${{ github.event.inputs.version }}.tar.gz
        if-no-files-found: error

  pip-test:
    name: Pip Test
    needs: build-sdist
    runs-on: ubuntu-latest
    steps:
    - name: Checkout pandas-release
      uses: actions/checkout@v2
    - name: Update conda
      uses: ./.github/actions/update-conda
    - name: Create conda environment
      run: |
        conda create -n pip-test -y python=3.7 numpy pytz python-dateutil pytest pytest-mock hypothesis nomkl
        conda clean --all
        conda list
    - name: get sdist from artifacts
      uses: actions/download-artifact@v2
      with:
        name: pandas-${{ github.event.inputs.version }}.tar.gz
        path: pandas/dist/
    - name: Create wheel
      run: |
        source activate pip-test
        python -m pip wheel --no-deps --wheel-dir=pandas/dist pandas/dist/pandas-${{ github.event.inputs.version }}.tar.gz
    - name: Install pandas
      run: |
        source activate pip-test
        python -m pip install --no-deps --no-index --find-links=pandas/dist --only-binary=pandas pandas
        conda list
    - name: Import pandas and print version
      run: |
        source activate pip-test
        python -c "import pandas as pd;print(pd.__version__)"
    - name: Test
      # test_missing_required_dependencies: https://github.com/pandas-dev/pandas/issues/33999
      run: |
        source activate pip-test
        python -c "import pandas; pandas.test(extra_args=['-m not clipboard', '--skip-slow', '--skip-network', '--skip-db', '-k not test_missing_required_dependency'])"

  conda-test:
    name: Conda Test
    needs: build-sdist
    runs-on: ubuntu-latest
    env:
      PANDAS_VERSION: ${{ github.event.inputs.version }}
    steps:
    - name: Checkout pandas-release
      uses: actions/checkout@v2
    - name: Update conda
      uses: ./.github/actions/update-conda
    - name: Create conda environment
      run: |
        conda create -n conda-build -y conda-build conda-verify gcc_linux-64 gxx_linux-64
        conda clean --all
        conda list
    - name: get sdist from artifacts
      uses: actions/download-artifact@v2
      with:
        name: pandas-${{ github.event.inputs.version }}.tar.gz
        path: pandas/dist/
    - name: Conda Build and Test
      run: |
        source activate conda-build
        conda build --numpy=1.17.3 --python=3.8 ./recipe --output-folder=pandas/dist

