# This is a basic workflow that is manually triggered

name: Manual Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '*/15 * * * *'
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'version'
        description: 'the pandas version to release'
        # Default value if no value is explicitly provided
        default: '1.1.2'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tag-release:
    name: Tag the release. (This doesn't push the tag)
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TAG: v${{ github.event.inputs.version }}
      GH_USERNAME: ${{ github.actor }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setting git user to Pandas Development Team
      run: |
       git config --global user.email "pandas-dev@python.org"
       git config --global user.name "Pandas Development Team"
    - name: Setting conda path
      run: echo ::add-path::$CONDA/bin
    - name: Update conda
      run: |
        conda config --set quiet true --set always_yes true
        conda update -n base -c defaults conda
        conda list
    - name: Checkout pandas-release
      uses: actions/checkout@v2
    - name: Update conda environment for release process
      run: |
        conda env update -n base --file=environment.yml
        conda list
    - name: Checkout pandas, pandas-wheels and pandas-feedstock
      run: make init-repos
    - name: Tag the release. (This doesn't push the tag)
      run: make tag
    - name: Store pandas directory as artifact
      uses: actions/upload-artifact@v2
      with:
        name: pandas
        path: pandas/

  build-sdist:
    name: Build the sdist
    needs: tag-release
    runs-on: ubuntu-latest
    steps:
    # Remove apt repos that are known to break from time to time 
    # See https://github.com/actions/virtual-environments/issues/323  
    # - name: Remove broken apt repos [Ubuntu]
    #   run: |
    #     for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
    - name: Update for build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get clean
    - name: Setting conda path
      run: echo ::add-path::$CONDA/bin
    - name: Update conda
      run: |
        conda config --set quiet true --set always_yes true
        conda update -n base -c defaults conda
        conda list
    - name: Update conda environment for build process
      run: |
        conda install -y conda-build conda-verify gcc_linux-64 gxx_linux-64 numpy pytz python-dateutil nomkl Cython
        conda clean --all
        conda list
    - name: Checkout pandas-release
      uses: actions/checkout@v2
    - name: get pandas directory from artifacts
      uses: actions/download-artifact@v2
      with:
        name: pandas
        path: pandas
    - name: build the sdist
      # from ./scripts/build_sdist.sh
      # git reset added since using artifacts seems to modify files
      working-directory: pandas
      run: |
        git status
        rm -rf dist
        git reset HEAD --hard
        git clean -xfd
        git status
        python setup.py clean --quiet
        python setup.py sdist --formats=gztar --quiet
    - name: pwd
      run: |
        pwd
        ls -latr
    - name: Store sdist archive as artifact
      uses: actions/upload-artifact@v2
      with:
        name: pandas-${{ github.event.inputs.version }}.tar.gz
        path: pandas/sdist/pandas-${{ github.event.inputs.version }}.tar.gz
