name: Create PDF Documentation

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'pandas version'
        default: '1.1.1'
        required: true

jobs:
  create-pdf:
    runs-on: ubuntu-latest
    env:
      TAG: v${{ github.event.inputs.version }}
    steps:
    - name: update runner environment and install pdflatex
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base xclip build-essential
        sudo apt-get clean
    - name: Setting conda path
      run: echo ::add-path::$CONDA/bin
    - name: Update conda
      run: |
        conda config --set quiet true --set always_yes true
        conda update -n base -c defaults conda
        conda list
    - name: Checkout pandas 
      run: |
        git clone https://github.com/pandas-dev/pandas
        cd pandas
        git status
        git checkout $TAG
    - name: Create conda environment
      run: |
        conda env create -n pandas --file=pandas/environment.yml
        source activate pandas
        conda uninstall -y --force pandas || true
        conda list
    - name: Build pandas from source
      working-directory: pandas
      run: |
        source activate pandas
        python setup.py build_ext -i -j 4
        python -c "import pandas as pd;pd.__version__"
    - name: Create HTML Documentation 
      working-directory: pandas/doc
      run: |
        source activate pandas
        ./make.py html
    - name: Create HTML Documentation (zipped) 
      working-directory: pandas/doc
      run: |
        source activate pandas
        ./make.py zip_html
    - name: Create PDF Documentation 
      working-directory: pandas/doc
      run: |
        source activate pandas
        ./make.py latex_forced