name: Create PDF Documentation

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'pandas version'
        default: '1.1.1'
        required: true

jobs:
  create-pdf:
    runs-on: ubuntu-latest
    env:
      TAG: v${{ github.event.inputs.version }}
    steps:
    - name: update runner environment and install pdflatex
      run: |
        sudo apt-get update
        # sudo apt-get install -y apt-get install texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra xclip build-essential
        sudo apt-get install -y texlive-full xclip build-essential
        sudo apt-get clean
    - name: Setting conda path
      run: echo ::add-path::$CONDA/bin
    - name: Update conda
      run: |
        conda config --set quiet true --set always_yes true
        conda update -n base -c defaults conda
        conda list
    - name: Checkout pandas 
      run: |
        git clone https://github.com/pandas-dev/pandas
        cd pandas
        git status
        git checkout $TAG
    - name: Create conda environment
      run: |
        conda env create -n pandas --file=pandas/environment.yml
        source activate pandas
        conda uninstall -y --force pandas || true
        conda list
    - name: Build pandas from source
      working-directory: pandas
      run: |
        source activate pandas
        python setup.py build_ext -i -j 4
        python -c "import pandas as pd;print(pd.__version__)"
    - name: Create HTML Documentation 
      working-directory: pandas/doc
      run: |
        source activate pandas
        ./make.py html
    - name: Create HTML Documentation (zipped) 
      working-directory: pandas/doc
      run: |
        source activate pandas
        ./make.py zip_html
    - name: Store zip archive as artifact
      uses: actions/upload-artifact@v2
      with:
        name: pandas.zip
        path: pandas/doc/build/html/pandas.zip
        if-no-files-found: error
    - name: Create PDF Documentation 
      working-directory: pandas/doc
      run: |
        source activate pandas
        ./make.py latex_forced || true
        ./make.py latex_forced
    - name: Store pdf as artifact
      uses: actions/upload-artifact@v2
      with:
        name: pandas.pdf
        path: pandas/doc/build/latex/pandas.pdf
        if-no-files-found: error
      if: always()
